# Generated by Django 6.0.1 on 2026-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('department', 'Department'), ('head', 'Head Authority'), ('worker', 'Worker')], max_length=20),
        ),
    ]
