# Generated by Django 6.0.1 on 2026-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('garbage', 'Garbage Department'), ('water', 'Water Department'), ('electricity', 'Electricity Department'), ('road', 'Road Department'), ('worker', 'Worker'), ('head', 'Head Authority')], max_length=20),
        ),
    ]
