# Generated by Django 6.0.1 on 2026-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('garbage', 'Garbage'), ('water', 'Water'), ('electricity', 'Electricity'), ('road', 'Road')], max_length=20, null=True),
        ),
    ]
