# Generated by Django 6.0.1 on 2026-03-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('department', 'Department'), ('worker', 'Worker'), ('head', 'Head Authority')], max_length=20),
        ),
    ]
