# Generated by Django 6.0.1 on 2026-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('department', 'Department'), ('worker', 'Worker'), ('head', 'Head Authority'), ('admin', 'Admin')], max_length=20),
        ),
    ]
