# Generated by Django 6.0.1 on 2026-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('garbage', 'Garbage'), ('water', 'Water'), ('electricity', 'Electricity'), ('road', 'Road'), ('health', 'Health'), ('traffic', 'Traffic'), ('transport', 'Transport'), ('education', 'Education')], max_length=20, null=True),
        ),
    ]
