# Generated by Django 6.0.1 on 2026-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_issue_title_issue_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
