# Generated by Django 6.0.1 on 2026-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_issue_is_escalated'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
