# Generated by Django 6.0.1 on 2026-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('road', 'Road'), ('water', 'Water'), ('electricity', 'Electricity'), ('garbage', 'Garbage')], max_length=50)),
                ('time_limit', models.FloatField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
