# Generated by Django 6.0.1 on 2026-03-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_departmentrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentrule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='departmentrule',
            name='penalty_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
